discoverers:
  marathon:
    - endpoints:
      -  http://marathon.mesos.stg.irl.aws.examplg.com/api
      template: |
        {{- $publicLB := "Z123456:public-123456.eu-west-1.elb.amazonaws.com."}}
        {{- $privateLB := "Z123456:private-123457.eu-west-1.elb.amazonaws.com."}}
        {{- range .Applications }} 
        {{- if (index .Labels "dnsName") }}
        {{- if eq (index .Labels "externalAccess") "public" }}
        {{ index .Labels "dnsName"}} 0 A 0.0.0.0 ; route53.Alias={{$publicLB}}
        {{- else }}
        {{ index .Labels "dnsName"}} 0 A 0.0.0.0 ; route53.Alias={{$privateLB}}
        {{- end }}
        {{- end }}
        {{- end }}

provisioners:
  route53:
    - zone: examplg.com.
      zoneid: Z23456

