#{{ index .Labels "elb_dns_name"}} A 0.0.0.0 ; {{or (index .Labels "elb_security_groups") "private"}}
#{{ index .Labels "elb_dns_name"}} A 0.0.0.0 ; {{or (index .Labels "elb_security_groups") "private"}}

discoverers:
  marathon:
    - endpoints:
      -  http://marathon.mesos.stg.irl.aws.qutics.com/api
      template: |
        {{- $publicLB := "1234:dualstak.public"}}
        {{- $privateLB := "1234:dualstak.private"}}
        {{- range .Applications }} 
        {{- if (index .Labels "traefik.dnsName") }}
        {{- if eq (index .Labels "traefik.externalAccess") "public" }}
        {{ index .Labels "traefik.dnsName"}} A 0.0.0.0 ; route53.Alias={{$publicLB}}
        {{- else }}
        {{ index .Labels "traefik.dnsName"}} A 0.0.0.0 ; route53.Alias={{$privateLB}}
        {{- end }}
        {{- end }}
        {{- end }}

provisioners:
  route53:
    - zone: qutics.com.
    - zone: qubit.com.
  cloudflare:
    - zone: curlpipesh.it.

